server:
    port: 8080

spring:
    datasource:
        username: root
        password: sk211314
        url: jdbc:mysql://localhost:3306/machine?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
        driver-class-name: com.mysql.cj.jdbc.Driver
    mvc:
        static-path-pattern: /static/**

mybatis:
    mapper-locations: classpath:mapping/*Mapper.xml
    type-aliases-package: org.fkit.springbootmybatistest.entity


#showSql
logging:
  level:
    com:
        example:
            mapper: debug

thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    mode: html5
    servlet:
        content-type: text/html

